// ── Kickoff Questionnaire — exact data from Excel ────────────
export const DEFAULT_QUESTIONNAIRE = {
  id: 'tpl-questionnaire', name: 'Kickoff Questionnaire',
  version: '1.0', updated: '2026-05-05',
  sections: [
    { name: 'Scope', questions: [
      'What is the business objective for implementing PriceMaster? How many teams/users will log into the PM?',
      'Which asset classes are in scope (current and future)?',
      'Can the same security have different prices by fund?',
    ]},
    { name: 'Security & Position', questions: [
      'Which securities should be priced (held only / watchlist / all)?',
      'What is the expected security and fund volume?',
      'How frequently are new positions added (real-time / intraday / EOD)?',
      'Do new positions require immediate pricing?',
    ]},
    { name: 'Pricing Frequency', questions: [
      'What is the pricing frequency (daily / weekly / monthly / ad-hoc)?',
      'Are any securities priced less frequently (e.g., quarterly) in case of daily/monthly pricing?',
      'Should stale prices be flagged as exceptions?',
    ]},
    { name: 'Pricing Sources', questions: [
      'What pricing source types are used (vendor, broker, exchange, internal)?',
      'Are multiple sources used for the same security?',
    ]},
    { name: 'Exceptions', questions: [
      'What are key exceptions need to be monitored or flagged in PriceMaster? (Stale Price/Missing Price etc)',
    ]},
    { name: 'Solicitation', questions: [
      'Is price solicitation required?',
      'Who initiates solicitation (system or user)?',
      'Are prices solicited from brokers, vendors, or both?',
      'Does solicitation vary by asset class?',
      'Is there a defined SLA for solicitation responses?',
      'Are multiple solicitation rounds or reminders allowed?',
    ]},
    { name: 'Challenges', questions: [
      'Is a formal price challenge process required with vendors or brokers?',
      'Who initiates price challenges?',
      'What are the key challenge triggers (variance, stale price, etc.)?',
      'Is supporting commentary or evidence required?',
      'Can challenges be reopened or re-challenged?',
      'How should challenge outcomes be handled (accept / override)?',
      'Are challenges user-driven, rule-based, or both?',
    ]},
    { name: 'Overrides', questions: [
      'Are manual price overrides allowed?',
      'Do overrides require justification and approval?',
    ]},
    { name: 'Approval Workflow', questions: [
      'What approval workflow is required (maker–checker / multi-level)?',
      'What are the pricing cut-off times?',
      'Can prices be amended post sign-off?',
    ]},
    { name: 'Downstream', questions: [
      'Which functions consume prices (Accounting, Risk, Audit, etc.)?',
      'What is the reporting frequency (daily / month-end / quarter-end)?',
      'Which downstream systems receive prices?',
    ]},
    { name: 'Reporting', questions: [
      'What reports are required? (Price change/ Market Value Movement/ Stale Price Report)',
    ]},
    { name: 'Future', questions: [
      'Are additional asset classes expected?',
      'Is pricing volume expected to grow?',
    ]},
    { name: 'User Access & Roles', questions: [
      'Who will access PriceMaster and for what purpose?',
    ]},
    { name: 'Price Uploads', questions: [
      'Will users perform manual price uploads?',
      'What type of uploads are required (file, UI, override)?',
      'What is the expected volume of manual uploads?',
      'Will historical or backdated prices be uploaded or updated?',
      'What is the maximum lookback period for backdated uploads?',
    ]},
  ],
};

// ── Estimator Template ────────────────────────────────────────
export const DEFAULT_ESTIMATOR = {
  id: 'tpl-estimator', name: 'Estimator',
  version: '1.0', updated: '2026-05-05',
  steps: [
    { step: 'Environment setup',        base: 32,  mul: 'env',          role: 'Engineer' },
    { step: 'Installation',             base: 24,  mul: 'env',          role: 'Engineer' },
    { step: 'Security reference data',  base: 40,  mul: 'security',     role: 'Engineer' },
    { step: 'Positions data sources',   base: 14,  mul: 'positionSrc',  role: 'Engineer' },
    { step: 'Pricing data sources',     base: 14,  mul: 'pricingSrc',   role: 'Engineer' },
    { step: 'Custom code',              base: 40,  mul: 'customCode',   role: 'Engineer' },
    { step: 'Pricing rules',            base: 1.6, mul: 'pricingRules', role: 'BA + Eng' },
    { step: 'Exceptions',               base: 2,   mul: 'exceptions',   role: 'BA' },
    { step: 'Dashboards / Views',       base: 32,  mul: 'dashboards',   role: 'BA' },
    { step: 'Challenge & Solicitation', base: 24,  mul: 'challenge',    role: 'BA' },
    { step: 'Access management',        base: 16,  mul: 'access',       role: 'Engineer' },
    { step: 'Downstream reports',       base: 9,   mul: 'downstream',   role: 'Engineer' },
    { step: 'Reporting',                base: 40,  mul: 'reporting',    role: 'BA' },
    { step: 'UAT support & defect fix', base: 120, mul: 'uat',          role: 'Team' },
    { step: 'Prod-parallel + Go-live',  base: 72,  mul: 'golive',       role: 'Team' },
  ],
  inputs: {
    env: '2 envs', security: 'Standard (2-3 types)', positionSrc: '2-3 sources',
    pricingSrc: '3-4 sources', customCode: 'Moderate (200-1000 LOC)',
    pricingRules: 42, exceptions: 14, dashboards: 'Standard', challenge: 'Standard config',
    access: 'Standard', downstream: 6, reporting: 'Standard + custom',
    uat: 'Medium complexity', golive: 'Standard',
  },
  risks: {
    clientNew: true, clientITBottlenecks: false, multiSignoff: true,
    livingProd: false, regDeadline: false, greenfield: true, archetypeReusable: false,
  },
};

// ── Tasks — exact data from Impl_Tasks_and_Checklist.xlsx ─────
// Columns: phase, item, task, taskType, tags, responsible, owner, reviewer
export const DEFAULT_TASKS_RAW = [
  ['Project Creation','Project Creation','Get the team members allocated and signed off by project director','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Project Creation','Project Creation','Get the timesheet project created for the same by sending an email to allocation support','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Project Creation','Project Creation','Start regular client communication, twice a week as per PMO\'s instructions with weekly updates in a ppt','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Project Creation','Kick off Call','Schedule a kick off call with the client, with a ppt, breifing an overall timeline','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Analyse the security and position files, identify the primary identifier','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Decide the schedule and the frequency','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have all the vendor and dealers files been analysed properly? Is the format of the file discussed? Is the data readable and consumable? Have the data types been finalized?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have you maped the standard dictionary columns with price files? Are these signed off by Implementation Lead?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has a discussion happened between the PMDev team and Implementation team on any new file format - if it can be parsed or not?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have we identified which brokers can be automated and cannot be automated?','BA Checklist Item','','Implementation BA','','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Is the identifier and price column identified for each pricing file?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have we checked if the business day is available for all datasources - security, position, and pricing files? Either in filename or inside the file.','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','In case of monthly pricing, have we checked if the client requires month-end or last business day of the month?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','In case of monthly pricing, have we decided on all the tasks that will take place before month-end and post month-end (BD1, BD2, BD3, etc)','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Are we getting the business day in security filename, position filename and for all other datasources - either in filename or in a column','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Are the mode of integrations finalized for all datasources - security, position, pricing files and downstream posting','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','If the mail downloader is needed at the client, has a meeting been scheduled between the Dev/Implementation team and the client\'s technical team in case of client instance.','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have all the transformation rules and validation rules been finalized for all datasources - security, position and pricing files?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has the pricing hierarchy been discussed and analysed fully? Are the pricing rules sufficient enough to price all investment types?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Are the pricing checks analysed properly - if they are actually doable or not on Price Master?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has the client asked for any reports? If yes, are the reports and related requirements been discussed properly?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has the client asked for reconciliation of prices? If yes, is the benchmark price finalized?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Does the client require challenge and solicitation of prices? If yes, is the requirement discussed completely?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Is the downstream posting of prices discussed fully - what will be the mode of integration, frequency of the posting task, attributes to be posted?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has a discussion happened between the PMDev team and Implementation BA on client\'s custom requirements?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has the BRD been reviewed by peers or implementation lead?','BA Checklist Item','','Implementation Lead','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have we received any sort of final pricing output (non PM) from the client?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Get the BRD signed off by the client over email','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Get the implementation planned signed off by the client over email','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Sign off from implementation lead','BA Checklist Item','','Implementation Lead','',''],
  ['Implementation','Server setup (IVP Instance)','Have the server specs been finalized in case of a new server setup?','BA Checklist Item','','Key Account Manager/ Rajesh','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (IVP Instance)','Have we received the approval for new server cost from the client?','BA Checklist Item','','Key Account Manager/ Rajesh','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (IVP Instance)','Have the build team created the new server?','BA Checklist Item','','Build','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (IVP Instance)','In case of existing server, have we confirmed the other IVP products available?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (IVP Instance)','In case of existing server, have we informed the owners of other IVP products about the Price Master installation? Is the existing server capable of handling a new product?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (IVP Instance)','In case of SSO requirement, have we requested the users to be created on the client side?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Have we received the Dev/UAT server details from the client?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Have the service account been created to access the server? Does the service account has access to DB server and app server to run the installation?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Has the DB server details and login creds been shared with us?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Has the DBO account been created to access the DB server, having all the access required according to the PM Installation Guide?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Has MySQL been setup for EDM installation, according to the EDM Installation Guide?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Has the details for MySQL instance been shared with us? (required for EDM installation)','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Server readiness','Dev Task','','Implementation Engineer','',''],
  ['Implementation','Product Installation (IVP instance)','Is the Price Master and EDM installer package ready?','BA Checklist Item','','Dev/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (IVP instance)','Has the Price Master and EDM installer been shared with the build team?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (IVP instance)','Is the Price Master and EDM applicaton installed properly on the server?','BA Checklist Item','','Dev/Build/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (IVP instance)','In case excel add-in is required, has the installer been sent to the client IT team for installation on user machines?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (IVP instance)','In case excel add-in is required, is the excel add-in pointing to the correct server?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (IVP instance)','Is the PVC mounting setup properly, where all the assemblies will be stored for EDM?','BA Checklist Item','','Dev/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (IVP instance)','Has the app master been setup?','BA Checklist Item','','Dev/Build/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (Client instance)','Is the Price Master and EDM installer package ready?','BA Checklist Item','','Dev/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (Client instance)','Have all the pre-requisites been completed for Price Master installation, according to Price Master installation guide?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (Client instance)','Have the installation been done for Price Master and EDM?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (Client instance)','Are all the issues faced during installation raised back to Dev team as gaps found in the installation guide?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (Client instance)','In case excel add-in is required, has the installer been sent to the client IT team for installation on user machines?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (Client instance)','In case excel add-in is required, is the excel add-in pointing to the correct server?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation','Product Installation','Dev Task','','Implementation Engineer','',''],
  ['Implementation','Product Installation','Initial Common Configs setup','Dev Task','','Implementation BA','',''],
  ['Implementation','Product sanity testing - Dev or UAT environment','Is Price Master and EDM opening properly? Is the landing page opening smoothly?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product sanity testing - Dev or UAT environment','Are the users added to the applications? Are the users able to login into the application?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product sanity testing - Dev or UAT environment','Are all screens opening properly - blotter, asset analysis, price list, data sources?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product sanity testing - Dev or UAT environment','Is the SSO enabled, in case it is needed?','BA Checklist Item','','Build/Dev','Implementation BA','Implementation Lead'],
  ['Implementation','Product sanity testing - Dev or UAT environment','In case IVP SFTP server is needed, Has the SFTP been created by the build team? Have all the IPs been whitelisted? Has the public SSH key from the client been acquired and installed?','BA Checklist Item','','Build/Dev','Implementation BA','Implementation Lead'],
  ['Implementation','Product sanity testing - Dev or UAT environment','In case excel add-in is required, has the add-in been tested properly?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product setup','Are all the common configurations required, according to the BRD, been configured on Price Master?','BA Checklist Item','','Dev/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Mail-downloader setup','Have all the configs been done for mail downloader?','BA Checklist Item','','Dev/Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Mail-downloader setup','Is the mail downloader tested for all relevant domain emails','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Mail-downloader setup','Is the mail downloader tested for all extreme cases? (Filename a bit different, two similar files coming together)','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Have we checked the model and standard pipes that can be re-used?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Are the transport configurations properly set up? (SMTP, SQL, etc.)','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Are we following the standard pipe structure agreed for PM?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Has the standard dictionary for Brokers and other data sources (where standardization is possible) been prepared?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Are the variables on each pipe checked properly?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Are the pipes being reviewed by a senior implementation specialist?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Has the scheduling of pipes been done as per BRD?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','In case the flow of the standard pipe is not followed, have we maintained the pipes overview?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Security Pipe Creation','Dev Task','','Implementation Engineer','',''],
  ['Implementation','EDM pipes creation','Position Pipe Creation','Dev Task','','Implementation Engineer','',''],
  ['Implementation','Security and Position data setup','Are the security and position attributes and datasources created on Price Master?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Security and Position data setup','Are the securities getting loaded to the Price Master, after all transformations and validations, checked and verified - Count and attributes\' data','BA Checklist Item','','Implementation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Security and Position data setup','Is the count of positions getting loaded to the Price Master, after all transformations and validations, checked and verified - Count and attributes\' data','BA Checklist Item','','Implementation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Security and Position data setup','Is the count of final set of securities to be priced, post the static core and position core, checked and verified?','BA Checklist Item','','Implementation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Security and Position data setup','In case Proxy pricing is needed, is the RefMaster entity setup done?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Data Source pipe creation (create one task for each data source)','Dev Task','','Implementation Engineer','',''],
  ['Implementation','Price sources setup','Have we received the SFTP/API details from the vendors?','BA Checklist Item','','Implementation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Have we tested a few securities for each vendor using SFTP/API?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Is the count of securities being requested to the vendor verified? Most critical since involves cost to the client.','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Is the count of securities solicitated from vendors/dealers verified? Most critical since involves cost to the client.','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Are all the pricing attributes and datasources created on Price Master?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Are the pricing rules applied and verified?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Are all the exceptions created and tested?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Are all the relevant views been created and tested?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Is the testing been done for each price source? Are the securities that should get a price from the price source verified? Are the prices also verified? (Recon)','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','In case Proxy pricing is needed, is the Proxy Price setup done?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Is the challenge email going out correctly?','BA Checklist Item','','Implementation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Are we able to consume challenge response prices comfortably?','BA Checklist Item','','Implementation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Are the alerts in place for any new investment type added in the portfolio for which no rules are configured?','BA Checklist Item','','Implementation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','In case review level configs are required, are those been properly?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Calendar setup','Dev Task','','Implementation Engineer','',''],
  ['Implementation','Generic Loader','Setup generic loader (may need to split into multiple tasks)','Dev Task','','Implementation Engineer','',''],
  ['Implementation','Pricing & Exceptions Rules','Setup Pricing Rules','Dev Task','','Implementation BA','',''],
  ['Implementation','Pricing & Exceptions Rules','Setup Exception Rules','Dev Task','','Implementation BA','',''],
  ['Implementation','User setup','Are the users and groups created on Price Master?','Dev Task','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','User setup','Are the roles assigned to each user, accroding to the BRD?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','User setup','In case excel add-in is needed, are the privileges given to the users?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','User setup','Are the relevant users added to the pricelist - those who can view the prices?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','View Management','Has the user views been created?','Dev Task','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Approval Workflow','Approval workflow setup according to the BRD','Dev Task','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Reporting','Creation of Client Reports','Dev Task','','Implementation Engineer','',''],
  ['Implementation','Reporting','Standard product reports should be made available','BA Checklist Item','','Implementation BA','',''],
  ['Implementation','Downstream','Setup downstream systems and their posting (split into multiple tasks)','Dev Task','','Implementation Engineer','',''],
  ['Implementation','IVP Testing and User training','Has the final round of IVP testing been conducted?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','IVP Testing and User training','Are the user training sessions conducted? (Number of trainings according to the Impl plan)','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','IVP Testing and User training','Has the Implementation BA formally given approval on completion of all the items listed in Implementation plan to the Implementation Engineer?','BA Checklist Item','','Implementation BA','',''],
  ['Implementation','IVP Testing and User training','Has the confirmation email been sent to the client about the completion of IVP implementation and testing and the date of movement to UAT?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['UAT','Server setup (IVP Instance)','Have the build team created the new server (if required)?','BA Checklist Item','','Build','Implementation BA','Implementation Lead'],
  ['UAT','Server setup','Server readiness','Dev Task','','Implementation Engineer','',''],
  ['UAT','Product Installation (IVP Instance)','Has the Price Master and EDM been cloned on the UAT server?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (IVP Instance)','In case cloning is not done, has the Price Master and EDM installer been shared with the build team?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (IVP Instance)','Is the Price Master and EDM applicaton installed properly on the server?','BA Checklist Item','','Dev/Build/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (IVP Instance)','Are the EDM pipes properly migrated from DEV to UAT server? Are all the pipes properly tested?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (IVP Instance)','Are the transport configs updated in EDM?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (IVP Instance)','In case excel add-in is required, has the installer been sent to the client IT team for installation on user machines?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (IVP Instance)','In case excel add-in is required, is the excel add-in pointing to the correct server?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (IVP Instance)','Is the PVC mounting setup properly, where all the assemblies will be stored for EDM?','BA Checklist Item','','Dev/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (Client instance)','Is the Price Master and EDM installer package ready?','BA Checklist Item','','Dev/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (Client instance)','Have all the pre-requisites been completed for Price Master installation, according to Price Master installation guide?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (Client instance)','Have the installation been done for Price Master and EDM?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (Client instance)','Are all the issues faced during installation raised back to Dev team as gaps found in the installation guide?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (Client instance)','Are the EDM pipes properly migrated from DEV to UAT server? In case MySQL has been cloned, are all the pipes properly tested?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (Client instance)','Are the transport configs updated in EDM?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (Client instance)','In case excel add-in is required, has the installer been sent to the client IT team for installation on user machines?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['UAT','Product Installation (Client instance)','In case excel add-in is required, is the excel add-in pointing to the correct server?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['UAT','Product sanity testing - Dev or UAT environment','Is Price Master and EDM opening properly? Is the landing page opening smoothly?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product sanity testing - Dev or UAT environment','Are the users added to the applications? Are the users able to login into the application?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Product sanity testing - Dev or UAT environment','Are all screens opening properly - blotter, asset analysis, price list, data sources?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Mail-downloader setup','Have all the configs been done for mail downloader?','BA Checklist Item','','Dev/Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Mail-downloader setup','Is the mail downloader tested for all relevant domain emails','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Mail-downloader setup','Is the mail downloader tested for all extreme cases? (Filename a bit different, two similar files coming together)','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','IVP Testing and User training','Has full-fledged IVP price testing been conducted on the UAT server?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['UAT','IVP Testing and User training','Are the user training sessions conducted? (Number of trainings according to the Impl plan)','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['UAT','IVP Testing and User training','Have all the client issues raised during UAT been addressed?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','Client Testing','Verify the complete end-to-end Valuation Workflow','Dev Task','','Client','',''],
  ['UAT','Client Testing','Verify all Prices / Exceptions and Alerts','Dev Task','','Client','',''],
  ['UAT','Client Testing','Data Reconciliation','Dev Task','','Client','',''],
  ['UAT','IVP Testing and User training','Have we received UAT sign-off to move to prod?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup','Server readiness','Dev Task','','Implementation Engineer','',''],
  ['Prod Live','Server setup (IVP Instance)','Have the build team created the new server (if required)?','BA Checklist Item','','Build','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (IVP Instance)','In case of existing server, have we confirmed the other IVP products available?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (IVP Instance)','In case of existing server, have we informed the owners of other IVP products about the Price Master installation? Is the existing server capable of handling a new product?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (IVP Instance)','Has the DB been restored?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (IVP Instance)','Has the DB server details and login creds been shared with us? (For transport configs)','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Have we received the Dev/UAT server details from the client?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Have the service account been created to access the server? Does the service account has access to DB server and app server to run the installation?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Has the DB been restored from Dev to UAT?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Has the DB server details and login creds been shared with us?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Are the DB maintenance jobs set up for the PriceMaster DB?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Is the cleanup facility setup at the application server? (Keeping files for last 3 months only)','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Has the DBO account been created to access the DB server, having all the access required according to the PM Installation Guide?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Has MySQL been setup for EDM installation, according to the EDM Installation Guide?','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Server setup (Client Instance)','Has the details for MySQL instance been shared with us? (required for EDM installation)','BA Checklist Item','','Implemenation Engineer/BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation','Run product installations','Dev Task','','Implementation Engineer','',''],
  ['Prod Live','Product Installation','Setup initial configs','Dev Task','','Implementation BA','',''],
  ['Prod Live','Product Installation (IVP Instance)','Is the Price Master and EDM installer package ready?','BA Checklist Item','','Dev/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','Has the Price Master and EDM been cloned on the Prod server?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','In case cloning is not done, has the Price Master and EDM installer been shared with the build team?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','Is the Price Master and EDM applicaton installed properly on the server?','BA Checklist Item','','Dev/Build/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','Are the EDM pipes properly migrated from DEV to UAT server? Are all the pipes properly tested?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','Are the tasks failures at Price Master (Static, Position, and Pricing Core) subscribed?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','Are the email alerts enabled for all the pipes that failed to run?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','Are the transport configs updated in EDM?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','In case excel add-in is required, has the installer been sent to the client IT team for installation on user machines?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (IVP Instance)','In case excel add-in is required, is the excel add-in pointing to the correct server?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','Is the Price Master and EDM installer package ready?','BA Checklist Item','','Dev/Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','Have all the pre-requisites been completed for Price Master installation, according to Price Master installation guide?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','Have the installation been done for Price Master and EDM?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','Are all the issues faced during installation raised back to Dev team as gaps found in the installation guide?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','Are the EDM pipes properly migrated from DEV to UAT server? In case MySQL has been cloned, are all the pipes properly tested?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','Are the tasks failures at Price Master (Static, Position, and Pricing Core) subscribed?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','Are the email alerts enabled for all the pipes that failed to run?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','Are the transport configs updated in EDM?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','In case excel add-in is required, has the installer been sent to the client IT team for installation on user machines?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation (Client instance)','In case excel add-in is required, is the excel add-in pointing to the correct server?','BA Checklist Item','','Client IT/Dev','Implementation BA','Implementation Lead'],
  ['Prod Live','Product sanity testing - Prod environment','Is Price Master and EDM opening properly? Is the landing page opening smoothly?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product sanity testing - Prod environment','Are the users added to the applications? Are the users able to login into the application?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Product sanity testing - Prod environment','Are all screens opening properly - blotter, asset analysis, price list, data sources?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Mail-downloader setup','Have all the configs been done for mail downloader?','BA Checklist Item','','Dev/Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Mail-downloader setup','Is the mail downloader tested for all relevant domain emails','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Mail-downloader setup','Is the mail downloader tested for all extreme cases? (Filename a bit different, two similar files coming together)','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Prod Live','Client Sanity','Verification and Sanity of Prod environment','Dev Task','','Client','',''],
  ['Support handover','Users setup','Are all the users from support who would be working on the project formally signed off by Support DAD?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Support handover','Users setup','Is the client approval taken to give PM access to support users?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Support handover','Handover plan','Has the KT handover plan been prepared?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Support handover','Handover plan','Has all the pipes overview given to the support team?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Support handover','Handover plan','Are all the special/cases done for the client discussed with support team?','BA Checklist Item','','Implemenation Engineer','Implementation BA','Implementation Lead'],
  ['Support handover','Product setup','Are the email alerts to the support team enabled for all the pipes that failed to run?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Support handover','Product setup','Are the support members subscribed to all Price Master task failures? (Static, Position and Price Core)','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
];

// ── RAID Log defaults — exact data from RAID_Log.xlsx ─────────
export const DEFAULT_RAID_ROWS = [
  { classification: 'Dependency', item: 'Sec Ref Integration',  details: 'E.g., Format and mode of integration for Sec Master data needs to be confirmed', raisedOn: '2026-03-15', pendingWith: 'Client',  updates: '4-Apr-26: Discussion with client IT started', status: 'In Progress',   eta: '',           comments: '' },
  { classification: 'Dependency', item: 'Vendor 1 Integration', details: 'FTP details yet to be agreed upon with vendor',                                      raisedOn: '2026-03-15', pendingWith: 'Vendor',  updates: '',                                       status: 'Not Initiated', eta: '',           comments: '' },
  { classification: 'Risk',       item: 'Pricing Rules',        details: 'Pricing Hierarchy is still not confirmed. It may lead to delay in project.',          raisedOn: '2026-03-20', pendingWith: 'Client',  updates: '',                                       status: 'In Progress',   eta: '2026-04-15', comments: '' },
];

export const ADMIN_LISTS = {
  phases: ['Project Creation', 'Requirement Gathering', 'Implementation', 'UAT', 'Prod Live', 'Support handover'],
  statuses: ['Not Started', 'In Progress', 'Done', 'Blocked', 'Delayed', 'Under Review'],
  people: ['Priya M.', 'Rohan K.', 'Suresh V.', 'Anand R.', 'Meera S.', 'Implementation Lead', 'Implementation BA', 'Implementation Engineer', 'Rajesh P.', 'Vikram S.'],
  responsibles: ['Implementation BA', 'Implementation Lead', 'Implementation Engineer', 'Implemenation Engineer/BA', 'Implementation Engineer/BA', 'Dev/Implementation Engineer', 'Dev/Build/Implementation Engineer', 'Build', 'Key Account Manager/ Rajesh', 'Client IT/Dev', 'Client'],
};

export const RAID_CLASSIFICATIONS = ['Risk', 'Action', 'Issue', 'Dependency', 'Decision', 'Assumption'];
export const RAID_STATUSES = ['Not Initiated', 'In Progress', 'Completed', 'Closed', 'Escalated'];
export const RAID_PENDING = ['Client', 'Vendor', 'IVP BA', 'IVP Engineer', 'IVP Lead', 'Build Team'];
