// ── Default Questionnaire Template ──────────────────────────
export const DEFAULT_QUESTIONNAIRE = {
  id: 'tpl-questionnaire', name: 'Kickoff Questionnaire',
  version: '1.0', updated: '2026-05-05',
  sections: [
    { name: 'Scope', questions: ['What is the business objective for implementing PriceMaster? How many teams/users will log into the PM?', 'Which asset classes are in scope (current and future)?', 'Can the same security have different prices by fund?'] },
    { name: 'Security & Position', questions: ['Which securities should be priced (held only / watchlist / all)?', 'What is the expected security and fund volume?', 'How frequently are new positions added (real-time / intraday / EOD)?', 'Do new positions require immediate pricing?'] },
    { name: 'Pricing Frequency', questions: ['What is the pricing frequency (daily / weekly / monthly / ad-hoc)?', 'Are any securities priced less frequently (e.g., quarterly) in case of daily/monthly pricing?', 'Should stale prices be flagged as exceptions?'] },
    { name: 'Pricing Sources', questions: ['What pricing source types are used (vendor, broker, exchange, internal)?', 'Are multiple sources used for the same security?'] },
    { name: 'Exceptions', questions: ['What are key exceptions that need to be monitored or flagged in PriceMaster? (Stale Price / Missing Price etc.)'] },
    { name: 'Solicitation', questions: ['Is price solicitation required?', 'Who initiates solicitation (system or user)?', 'Are prices solicited from brokers, vendors, or both?', 'Does solicitation vary by asset class?', 'Is there a defined SLA for solicitation responses?', 'Are multiple solicitation rounds or reminders allowed?'] },
    { name: 'Challenges', questions: ['Is a formal price challenge process required with vendors or brokers?', 'Who initiates price challenges?', 'What are the key challenge triggers (variance, stale price, etc.)?', 'Is supporting commentary or evidence required?', 'Can challenges be reopened or re-challenged?', 'How should challenge outcomes be handled (accept / override)?', 'Are challenges user-driven, rule-based, or both?'] },
    { name: 'Overrides', questions: ['Are manual price overrides allowed?', 'Do overrides require justification and approval?'] },
    { name: 'Approval Workflow', questions: ['What approval workflow is required (maker–checker / multi-level)?', 'What are the pricing cut-off times?', 'Can prices be amended post sign-off?'] },
    { name: 'Downstream', questions: ['Which functions consume prices (Accounting, Risk, Audit, etc.)?', 'What is the reporting frequency (daily / month-end / quarter-end)?', 'Which downstream systems receive prices?'] },
    { name: 'Reporting', questions: ['What reports are required? (Price change / Market Value Movement / Stale Price Report)'] },
    { name: 'Future', questions: ['Are additional asset classes expected?', 'Is pricing volume expected to grow?'] },
    { name: 'User Access & Roles', questions: ['Who will access PriceMaster and for what purpose?'] },
    { name: 'Price Uploads', questions: ['Will users perform manual price uploads?', 'What type of uploads are required (file, UI, override)?', 'What is the expected volume of manual uploads?', 'Will historical or backdated prices be uploaded or updated?', 'What is the maximum lookback period for backdated uploads?'] },
  ],
};

// ── Default Estimator Template ───────────────────────────────
export const DEFAULT_ESTIMATOR = {
  id: 'tpl-estimator', name: 'Estimator',
  version: '1.0', updated: '2026-05-05',
  steps: [
    { step: 'Environment setup',        base: 32,  mul: 'env',          role: 'Engineer' },
    { step: 'Installation',             base: 24,  mul: 'env',          role: 'Engineer' },
    { step: 'Security reference data',  base: 40,  mul: 'security',     role: 'Engineer' },
    { step: 'Positions data sources',   base: 14,  mul: 'positionSrc',  role: 'Engineer' },
    { step: 'Pricing data sources',     base: 14,  mul: 'pricingSrc',   role: 'Engineer' },
    { step: 'Custom code',              base: 40,  mul: 'customCode',   role: 'Engineer' },
    { step: 'Pricing rules',            base: 1.6, mul: 'pricingRules', role: 'BA + Eng' },
    { step: 'Exceptions',               base: 2,   mul: 'exceptions',   role: 'BA' },
    { step: 'Dashboards / Views',       base: 32,  mul: 'dashboards',   role: 'BA' },
    { step: 'Challenge & Solicitation', base: 24,  mul: 'challenge',    role: 'BA' },
    { step: 'Access management',        base: 16,  mul: 'access',       role: 'Engineer' },
    { step: 'Downstream reports',       base: 9,   mul: 'downstream',   role: 'Engineer' },
    { step: 'Reporting',                base: 40,  mul: 'reporting',    role: 'BA' },
    { step: 'UAT support & defect fix', base: 120, mul: 'uat',          role: 'Team' },
    { step: 'Prod-parallel + Go-live',  base: 72,  mul: 'golive',       role: 'Team' },
  ],
  inputs: {
    assetClasses: 6, positionSources: 4, pricingSources: 4,
    downstreamConsumers: 6, dailyVolume: '10K-100K',
    customCode: 'Moderate (200-1000 LOC)', pricingRulesCount: 42, exceptionTypes: 14,
    challengeMode: 'Standard config', regComplexity: 'Medium (SEC)',
  },
  risks: {
    clientNew: true, clientITBottlenecks: false, multiSignoff: true,
    livingProd: false, regDeadline: false, greenfield: true, archetypeReusable: false,
  },
};

// ── Admin Lists ──────────────────────────────────────────────
export const ADMIN_LISTS = {
  phases: ['Project Creation', 'Requirement Gathering', 'Implementation', 'UAT', 'Prod Live', 'Support handover'],
  statuses: ['Not Started', 'In Progress', 'Done', 'Blocked', 'Delayed', 'Under Review'],
  people: ['Priya M.', 'Rohan K.', 'Suresh V.', 'Anand R.', 'Meera S.', 'Implementation Lead', 'Implementation BA', 'Implementation Engineer', 'Rajesh P.', 'Vikram S.'],
  responsibles: ['Implementation BA', 'Implementation Lead', 'Implementation Engineer', 'Key Account Manager/ Rajesh', 'Build', 'Client IT/Dev', 'Client'],
};

export const RAID_CLASSIFICATIONS = ['Risk', 'Action', 'Issue', 'Dependency', 'Decision', 'Assumption'];
export const RAID_STATUSES = ['Not Initiated', 'In Progress', 'Completed', 'Closed', 'Escalated'];
export const RAID_PENDING = ['Client', 'Vendor', 'IVP BA', 'IVP Engineer', 'IVP Lead', 'Build Team'];

// ── Default Tasks Raw ────────────────────────────────────────
export const DEFAULT_TASKS_RAW = [
  ['Project Creation','Project Creation','Get the team members allocated and signed off by project director','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Project Creation','Project Creation','Get the timesheet project created by sending an email to allocation support','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Project Creation','Project Creation','Start regular client communication, twice a week per PMO instructions with weekly updates in PPT','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Project Creation','Kick off Call','Schedule a kick off call with the client, with a PPT briefing an overall timeline','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Analyse the security and position files, identify the primary identifier','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Decide the schedule and the frequency','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have all vendor and dealer files been analysed?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have you mapped the standard dictionary columns with price files?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has a discussion happened between PMDev and Implementation team on any new file format?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have we identified which brokers can be automated and which cannot?','BA Checklist Item','','Implementation BA','','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Is the identifier and price column identified for each pricing file?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have we checked if the business day is available for all datasources?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','In case of monthly pricing, does client require month-end or last business day?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Are modes of integration finalised for all datasources?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','If mail downloader is needed, has a meeting been scheduled with client technical team?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Have all transformation and validation rules been finalised?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has the pricing hierarchy been fully discussed?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Are the pricing checks analysed properly?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has the client asked for any reports?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Does the client require challenge and solicitation?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Is downstream posting fully discussed?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has a discussion happened between PMDev and Implementation BA on client custom requirements?','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Has the BRD been reviewed by peers or Implementation Lead?','BA Checklist Item','','Implementation Lead','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Get the BRD signed off by the client over email','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Get the implementation plan signed off by the client over email','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Requirement Gathering','BRD Preparation','Sign off from Implementation Lead','BA Checklist Item','','Implementation Lead','',''],
  ['Implementation','Server setup (IVP Instance)','Have the server specs been finalised?','BA Checklist Item','','Key Account Manager/ Rajesh','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (IVP Instance)','Have we received approval for new server cost from the client?','BA Checklist Item','','Key Account Manager/ Rajesh','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (IVP Instance)','Have the build team created the new server?','BA Checklist Item','','Build','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Have we received the Dev/UAT server details from the client?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Have the service accounts been created with access to DB and app server?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Server setup (Client Instance)','Has the DBO account been created with all required access?','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Product Installation (IVP instance)','Install PriceMaster on IVP hosted server','BA Checklist Item','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Implementation','Product Installation (IVP instance)','Ensure PriceMaster services start without errors','BA Checklist Item','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Implementation','Product Installation (Client instance)','Install PriceMaster on client server','BA Checklist Item','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Implementation','Product Installation (Client instance)','Run installation validation checklist with client IT','BA Checklist Item','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Implementation','Product sanity testing - Dev or UAT environment','Login and basic navigation checks','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Product sanity testing - Dev or UAT environment','Check all menus and pages load without errors','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Product setup','Configure system parameters per BRD','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Product setup','Set up pricing calendar and business day rules','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Mail-downloader setup','Configure and test mail downloader end to end','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','EDM pipes creation','Create EDM pipes for security data','Dev Task','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Implementation','EDM pipes creation','Create EDM pipes for position data','Dev Task','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Implementation','EDM pipes creation','Create EDM pipes for pricing data','Dev Task','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Implementation','EDM pipes creation','Test all pipes end-to-end with sample data','Dev Task','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Implementation','Security and Position data setup','Map security master fields per BRD','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Security and Position data setup','Load initial security reference data','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Security and Position data setup','Validate positions data feed','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Configure vendor price source connections','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Configure broker price feeds','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Price sources setup','Test all price source connections','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Pricing & Exceptions Rules','Configure pricing hierarchy rules per BRD','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Pricing & Exceptions Rules','Configure exception rules (stale, missing, variance)','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Pricing & Exceptions Rules','Configure challenge and solicitation rules','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Pricing & Exceptions Rules','Unit test all pricing rules with known data','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','User setup','Create all user accounts per access matrix','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','User setup','Assign roles and permissions','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','View Management','Configure pricing views per requirements','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','View Management','Configure dashboard layouts','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Approval Workflow','Configure maker-checker workflow','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Approval Workflow','Test approval workflow end-to-end','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Reporting','Configure standard reports per BRD','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Reporting','Validate report output with client','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Implementation','Downstream','Configure downstream posting rules','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Implementation','Downstream','Test and validate downstream data feed','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['UAT','IVP Testing and User training','Conduct end-to-end IVP internal testing','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['UAT','IVP Testing and User training','Prepare and deliver user training materials','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['UAT','Client Testing','Share UAT test scripts with client','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['UAT','Client Testing','Support client during UAT execution','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['UAT','Client Testing','Log and fix UAT defects','Dev Task','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['UAT','Client Testing','Get UAT sign-off from client','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['UAT','Client Sanity','Run sanity checks post-fixes','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Product Installation','Install PriceMaster on production server','BA Checklist Item','','Implementation Engineer','Implementation Engineer','Implementation Lead'],
  ['Prod Live','Product sanity testing - Prod environment','Validate all integrations in production','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Product sanity testing - Prod environment','Parallel run: compare PM prices vs client legacy system','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Product sanity testing - Prod environment','Get production go-live approval from client','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Users setup','Create production user accounts','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Prod Live','Users setup','Confirm SSO / authentication working in prod','BA Checklist Item','','Implementation Engineer','Implementation BA','Implementation Lead'],
  ['Support handover','Handover plan','Prepare handover document for support team','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Support handover','Handover plan','Conduct knowledge transfer session with support team','BA Checklist Item','','Implementation BA','Implementation BA','Implementation Lead'],
  ['Support handover','Handover plan','Get sign-off on handover from client and support team','BA Checklist Item','SOCR','Implementation BA','Implementation BA','Implementation Lead'],
];
